# GitHub Secret Scanning Configuration
# This file tells GitHub to ignore certain files/directories from secret scanning

paths-ignore:
  # Ignore all test files (they contain fake API keys for validation testing)
  - "**/*.test.ts"
  - "**/*.spec.ts"
  # Specifically ignore the Stripe config test file
  - "src/config/stripe-config.test.ts"
  # Ignore any test directories
  - "tests/**"
  - "**/__tests__/**"

